### ISSUE TITLE
Latest commit didn't work

### ISSUE THREAD

**Issue by crackedmind** [Razzmatazzz/RemnantSaveGuardian#111]
41f6d0f8a33d8353e59241816769370029257aed

1) Compilation error: SettingsPage.xaml.cs:81 `Logger.Log(string.Join(", ", Loc.AvailableLocalizations()));`
2) Adventure tab not working

@Razzmatazzz did you forget to commit some stuff?

p.s. didn't forget update 1.0.2.0 tag after fix.

**Comment by Razzmatazzz** [comment]
Oops, yep, fixed now. Thanks!

**Comment by crackedmind** [comment]
Adventure tab still not working. It worked in uploaded 1.0.2.0 version.
